channels:
  - conda-forge
  - defaults
  - apple
dependencies:
  - python=3.9.16
  - tensorflow-deps
  - pip
  - pip:
    - mxnet~=1.6.0
    - pandas~=1.5.3
    - wheel
    - numpy~=1.23.5
    - scipy~=1.10.1
    - scikit-learn~=1.2.2
    - Cython~=0.29.34
    - vowpalwabbit~=9.8.0
    - lightgbm~=3.3.5
    - xgboost~=1.7.5
    - autogluon~=0.7.0
    - tensorflow-metal
    - tensorflow-macos
name: mlnanodegree

